# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: particles.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='particles.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fparticles.proto\":\n\x08Particle\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\r\n\x05theta\x18\x04 \x01(\x02\",\n\x0cParticleList\x12\x1c\n\tparticles\x18\x01 \x03(\x0b\x32\t.Particleb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PARTICLE = _descriptor.Descriptor(
  name='Particle',
  full_name='Particle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='Particle.w', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='Particle.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Particle.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theta', full_name='Particle.theta', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=77,
)


_PARTICLELIST = _descriptor.Descriptor(
  name='ParticleList',
  full_name='ParticleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='particles', full_name='ParticleList.particles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=123,
)

_PARTICLELIST.fields_by_name['particles'].message_type = _PARTICLE
DESCRIPTOR.message_types_by_name['Particle'] = _PARTICLE
DESCRIPTOR.message_types_by_name['ParticleList'] = _PARTICLELIST

Particle = _reflection.GeneratedProtocolMessageType('Particle', (_message.Message,), dict(
  DESCRIPTOR = _PARTICLE,
  __module__ = 'particles_pb2'
  # @@protoc_insertion_point(class_scope:Particle)
  ))
_sym_db.RegisterMessage(Particle)

ParticleList = _reflection.GeneratedProtocolMessageType('ParticleList', (_message.Message,), dict(
  DESCRIPTOR = _PARTICLELIST,
  __module__ = 'particles_pb2'
  # @@protoc_insertion_point(class_scope:ParticleList)
  ))
_sym_db.RegisterMessage(ParticleList)


# @@protoc_insertion_point(module_scope)
